apiVersion: v1
kind: PersistentVolume
metadata:
  name: customerdata-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/data/CustomerData
    server: x.x.x.x
